trigger: none

pool: default

stages:
  - stage: StageProvisionResourceGroup
    displayName: "Stage: Provision Resource Group"
    jobs:
      - job: JobProvisionResourceGroup
        displayName: "Job: Provision Resource Group"
        steps:          
          - task: AzurePowerShell@5
            inputs:
              azureSubscription: 'serviceconnectionprojectdaybreak'
              ScriptType: 'FilePath'
              ScriptPath: '$(System.DefaultWorkingDirectory)/scripts/create-resource-group.ps1'
              ScriptArguments: '-location northeurope `
                                -resourceGroupName "ydmlresources" `
                                -owner "dinesh" `
                                -costCenter "112245" `
                                -application "Project Day Break" `
                                -description "The latest AI to do AI things" `
                                -repo "https://yedladinesh3@dev.azure.com/yedladinesh3/Project%20Day%20Break/_git/pdb-provision-resource-groups.git"'
              FailOnStandardError: true
              azurePowerShellVersion: 'LatestVersion'
